# https://github.com/infinispan/infinispan/blob/15.2.1.Final/.github/workflows/tag.yml

name: Create Next Branch

on:
  workflow_call:
    inputs:
      current-version:
        description: "Release version"
        required: true
        type: string
        default: "0.0.1"
      next-version:
        description: "Next version"
        required: true
        type: string
        default: "0.0.2-SNAPSHOT"

permissions:
  contents: write
  issues: write

env:
  MAVEN_ARGS: -B -U -ntp

jobs:
  branch:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "CURRENT_VERSION=${DISPATCH_CURRENT_VERSION}" >> $GITHUB_ENV
          echo "NEXT_VERSION=${DISPATCH_NEXT_VERSION}" >> $GITHUB_ENV
          echo "NEXT_BRANCH=$(echo ${DISPATCH_NEXT_VERSION} | sed 's/-SNAPSHOT//')" >> $GITHUB_ENV
        env:
          DISPATCH_CURRENT_VERSION: ${{ inputs.current-version }}
          DISPATCH_NEXT_VERSION: ${{ inputs.next-version }}

      - name: Validate version
        if: contains(env.CURRENT_VERSION, 'SNAPSHOT')
        run: |
          echo '::error::CURRENT_VERSION cannot be a SNAPSHOT version.'
          exit 1

      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Set Release version
        run: |
          mvn -B versions:set -DprocessAllModules=true -DgenerateBackupPoms=false -DnewVersion=${CURRENT_VERSION}
          sed -i "s|<version>[0-9]\+\.[0-9]\+\.[0-9]\+</version>|<version>${CURRENT_VERSION}</version>|g" README.md
          git commit --no-verify -a -m "[CI Skip] Releasing ${CURRENT_VERSION}"

      - name: Create Tag
        run: |
          git tag -a "v${CURRENT_VERSION}" -m "Release v${CURRENT_VERSION}"

      - name: Create Branch
        run: |
          git branch -m ${NEXT_BRANCH}
          mvn versions:set -DprocessAllModules=true -DgenerateBackupPoms=false -DnewVersion=${NEXT_VERSION}
          git commit --no-verify -a -m "[CI Skip] Next version v${NEXT_BRANCH}"
          git push origin $(git rev-parse --abbrev-ref HEAD)

      - name: Release Milestone
        uses: rosestack/milestone-release-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          milestone-title: ${{ env.CURRENT_VERSION }}
          milestone-next: ${{ env.NEXT_BRANCH }}