name: Maven Build

on:
  workflow_call:

env:
  MAVEN_ARGS: -B -U -ntp

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[CI Skip]') && !contains(github.event.pull_request.title, '[CI Skip]')"
    strategy:
      matrix:
        java: [ '8', '11', '17', '21' ]

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.Java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Detect Maven Wrapper
        run: |
          if [ -f mvnw ]; then
            echo "MAVEN_EXEC=./mvnw" >> $GITHUB_ENV
          else
            echo "MAVEN_EXEC=mvn" >> $GITHUB_ENV
          fi

      - name: Build with Maven
        run: ${MAVEN_EXEC} package

  quality:
    needs: [ build ]
    if: "!contains(github.event.head_commit.message, '[CI Skip]') && !contains(github.event.pull_request.title, '[CI Skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'

      - name: Build with docs and coverage
        run: mvn install javadoc:javadoc jacoco:report

      - name: Build with sonar
        run: mvn sonar:sonar -Dsonar.token=${{secrets.SONAR_TOKEN}} -Dsonar.projectKey=$(echo ${{ github.repository }} | cut -d'/' -f2)

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
