# https://github.com/kanezi/boot-render-deploy/blob/master/.github/workflows/docker-publish.yml

name: Docker Publish by SpringBoot

on:
  workflow_call:
    inputs:
      java:
        default: '8'
        required: false
        type: string

      java-dist:
        default: 'zulu'
        required: false
        type: string

  workflow_dispatch:
    inputs:
      java:
        description: Java version to use
        default: '8'
        required: false
        type: string

      java-dist:
        description: Java distribution to use
        default: 'zulu'
        required: false
        type: string

env:
  MAVEN_ARGS: -V -ntp -U -B
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io

jobs:
  docker:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Java ${{ inputs.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java }}
          distribution: ${{ inputs.java-dist }}
          cache: maven

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Publish Docker Image
        run: |
          mvn spring-boot:build-image -DskipTests

          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          PROJECT_NAME=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/$PROJECT_NAME
          echo $IMAGE_NAME

          docker tag $PROJECT_NAME:$VERSION $IMAGE_NAME:latest
          echo "Pushing the image $IMAGE_NAME to ${{ env.REGISTRY }}..."
          docker push --all-tags $IMAGE_NAME
