# https://github.com/s4u/.github/blob/master/.github/workflows/maven-build.yml

name: Maven Deploy

on:
  workflow_call:
    inputs:
      java-default:
        default: '8'
        required: false
        type: string

      java-dist-default:
        default: 'zulu'
        required: false
        type: string

  workflow_dispatch:
    inputs:
      java-default:
        description: Java version to use
        default: '8'
        required: false
        type: string

      java-dist-default:
        description: Java distribution to use
        default: 'zulu'
        required: false
        type: string

env:
  MAVEN_ARGS: -B -U -ntp

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Java ${{ inputs.java-default }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-default }}
          distribution: ${{ inputs.java-dist-default }}
          cache: maven
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # macOS: gpg --armor --export-secret-key

      - run: mvn -DskipTests -Prelease deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/*.jar
            target/*.pom
            target/*.asc
            target/*.md5
            target/*.sha1
            target/*.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
