# https://github.com/s4u/.github/blob/master/.github/workflows/maven-build.yml

name: Maven Build

on:
  workflow_call:
    inputs:
      os:
        default: '["windows-latest", "ubuntu-latest", "macOs-latest"]'
        required: false
        type: string

      java-matrix:
        default: '["8", "11", "17", "21", "24"]'
        required: false
        type: string

      java-dist-matrix:
        default: '["zulu"]'
        required: false
        type: string

      sonar-host:
        default: 'https://sonarcloud.io/'
        required: false
        type: string

      sonar-organization:
        default: 'rosestack'
        required: false
        type: string

  workflow_dispatch:
    inputs:
      os:
        description: OS
        default: '["windows-latest", "ubuntu-latest", "macOs-latest"]'
        required: false
        type: string

      java-matrix:
        description: Java Version
        default: '["8", "11", "17", "21", "24"]'
        required: false
        type: string

      java-dist-matrix:
        description: Java Distribution
        default: '["zulu"]'
        required: false
        type: string

      sonar-host:
        description: Sonar Host
        default: 'https://sonarcloud.io/'
        required: false
        type: string

      sonar-organization:
        description: Sonar Organization
        default: 'rosestack'
        required: false
        type: string

env:
  MAVEN_ARGS: -B -U -ntp

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  build:
    name: ${{ matrix.os }}-jdk-${{ matrix.java }}-${{ matrix.java-dist }}
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    if: "!contains(github.event.head_commit.message, '[CI Skip]') && !contains(github.event.pull_request.title, '[CI Skip]')"

    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON( inputs.os ) }}
        java: ${{ fromJSON( inputs.java-matrix ) }}
        java-dist: ${{ fromJSON( inputs.java-dist-matrix ) }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.Java }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.java-dist }}
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Build with Maven
        run: mvn verify

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        if: >
          matrix.os == 'ubuntu-latest'
          && matrix.java == '17'
          && startsWith( github.ref, 'refs/heads/')
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
