# https://github.com/smallrye/smallrye-config/blob/main/.github/workflows/prepare-release.yml

name: Maven Release File

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]
    paths:
      - '.github/project.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: rosestack/maven-release-by-file-action@main
        with:
          gpg-secret-key: ${{secrets.GPG_SECRET_KEY}}
          gpg-passphrase: ${{secrets.GPG_PASSPHRASE}}
          ossrh-username: ${{secrets.OSSRH_USERNAME}}
          ossrh-password: ${{secrets.OSSRH_PASSWORD}}
          github-token: ${{secrets.GITHUB_TOKEN}}
