name: Maven Release Manual

on:
  workflow_dispatch:
    inputs:
      current-version:
        description: "Release version"
        required: true
        default: "0.0.1"
      next-version:
        description: "Next version"
        required: true
        default: "0.0.2-SNAPSHOT"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: rosestack/maven-release-by-manual-action@main
        with:
          current-version: ${{github.event.inputs.current-version}}
          next-version: ${{github.event.inputs.next-version}}
          gpg-secret-key: ${{secrets.GPG_SECRET_KEY}}
          gpg-passphrase: ${{secrets.GPG_PASSPHRASE}}
          ossrh-username: ${{secrets.OSSRH_USERNAME}}
          ossrh-password: ${{secrets.OSSRH_PASSWORD}}
          github-token: ${{secrets.GITHUB_TOKEN}}
