# https://www.lorenzobettini.it/2020/01/publishing-a-maven-site-to-github-pages

name: Maven Test

on:
  workflow_call:
    inputs:
      java:
        default: '8'
        required: false
        type: string

      java-dist:
        default: 'zulu'
        required: false
        type: string

env:
  MAVEN_ARGS: -B -U -ntp

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.Java }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.Java-dist }}
          java-version: ${{ matrix.Java }}
          cache: maven

      - name: Maven Test
        run: |
          mvn package
