# https://github.com/smallrye/smallrye-config/blob/main/.github/workflows/prepare-release.yml

name: Maven Release By File

##
## Automates the release process
## 1. Edit the file .github/project.yml, update version.
## 2. Commit
## 3. Create PR, merge PR
##

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]
    paths:
      - '.github/project.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: rosestack/maven-release-by-file-action@v1.3
        with:
          gpg-secret-key: ${{secrets.GPG_PRIVATE_KEY}}
          gpg-passphrase: ${{secrets.GPG_PASSPHRASE}}
          ossrh-username: ${{secrets.MAVEN_USERNAME}}
          ossrh-password: ${{secrets.MAVEN_PASSWORD}}
          github-token: ${{secrets.GITHUB_TOKEN}}
