# https://www.lorenzobettini.it/2020/01/publishing-a-maven-site-to-github-pages

name: Maven Site and Publish

on:
  workflow_call:
    inputs:
      java:
        default: '8'
        required: false
        type: string

      java-dist:
        default: 'zulu'
        required: false
        type: string

    secrets:
      OSSRH_USERNAME:
        required: true

      OSSRH_PASSWORD:
        required: true

      GPG_SECRET_KEY:
        required: true

      SIGNING_PASSPHRASE:
        required: true

env:
  MAVEN_ARGS: -B -U -ntp

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Java ${{ inputs.java-default }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-default }}
          distribution: ${{ inputs.java-dist-default }}
          cache: maven
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }} # macOS: gpg --armor --export-secret-key

      - run: mvn -DskipTests -Prelease deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.SIGNING_PASSPHRASE }}
