# https://github.com/kanezi/boot-render-deploy/blob/master/.github/workflows/docker-publish.yml

name: Maven Docker

on:
  workflow_call:
    inputs:
      os:
        default: '["ubuntu-latest"]'
        required: false
        type: string

      java-matrix:
        default: '["8"]'
        required: false
        type: string

      java-dist-matrix:
        default: '["zulu"]'
        required: false
        type: string

  workflow_dispatch:
    inputs:
      os:
        default: '["ubuntu-latest"]'
        description: OS
        required: false
        type: string

      java-matrix:
        description: Java Version
        default: '["8"]'
        required: false
        type: string

      java-dist-matrix:
        description: Java Distribution
        default: '["zulu"]'
        required: false
        type: string

env:
  MAVEN_ARGS: -B -U -ntp
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
#  IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: rosestack/test

jobs:
  build:
    uses: ./.github/workflows/maven-build.yml
    secrets: inherit
    with:
      os: ${{inputs.os}}
      java-matrix: ${{inputs.java-matrix}}
      java-dist-matrix: ${{inputs.java-dist-matrix}}

  docker:
    runs-on: ubuntu-latest
    needs: build
    # if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Publish Docker Image
        run: |
          mvn spring-boot:build-image -DskipTests Dspring-boot.build-image.imageName=${{ env.IMAGE_NAME }}
          TAG=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          docker tag ${{ env.IMAGE_NAME }}:$TAG ${{ env.IMAGE_NAME }}:latest
          echo "Pushing the image ${{ env.IMAGE_NAME }} to ${{ env.REGISTRY }}..."
          docker push --all-tags ${{ env.IMAGE_NAME }}