name: Maven Prepare Release

##
## Automates the release process
## 1. Run workflow `maven-prepare-release.yml` in actions
##

on:
  workflow_call:
    inputs:
      release-version:
        description: "Release version"
        required: true
        type: string
        default: "0.0.1"
      next-version:
        description: "Next version"
        required: true
        type: string
        default: "0.0.2-SNAPSHOT"

  workflow_dispatch:
    inputs:
      release-version:
        description: "Release version"
        required: true
        type: string
        default: "0.0.1"
      next-version:
        description: "Next version"
        required: true
        type: string
        default: "0.0.2-SNAPSHOT"

env:
  MAVEN_ARGS: -V -ntp -U -B

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "RELEASE_VERSION=${DISPATCH_RELEASE_VERSION}" >> $GITHUB_ENV
          echo "NEXT_VERSION=${DISPATCH_NEXT_VERSION}" >> $GITHUB_ENV
        env:
          DISPATCH_RELEASE_VERSION: ${{ inputs.release-version }}
          DISPATCH_NEXT_VERSION: ${{ inputs.next-version }}

      - name: Validate version
        if: contains(env.RELEASE_VERSION, 'SNAPSHOT')
        run: |
          echo '::error::Cannot release a SNAPSHOT version.'
          exit 1

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'zulu'
          cache: maven
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # macOS: gpg --armor --export-secret-key

      - name: Get version
        run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "VERSION=$VERSION"
          if [[ $VERSION != *-SNAPSHOT ]]; then
            echo "::error::You don't have a SNAPSHOT project in the projects list."
            exit 1
          fi

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Build Prepare Release with Maven
        timeout-minutes: 120
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo $BRANCH

          git checkout -b "release-$RELEASE_VERSION"

          mvn release:prepare -DinteractiveMode=false -DnoBackup=true -DreleaseVersion=$RELEASE_VERSION -Dtag=v$RELEASE_VERSION -DdevelopmentVersion=$NEXT_VERSION

          git push origin "release-$RELEASE_VERSION"

          mvn -Prelease clean package source:jar javadoc:jar gpg:sign deploy site site:stage

          git checkout $BRANCH

          git branch -D "release-$RELEASE_VERSION"

          git push --tags
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Create Github Release
        uses: softprops/action-gh-release@v2.3.2

#      - name: Create Github Release
#        run: |
#          gh release create v${RELEASE_VERSION} --generate-notes
#        env:
#          GITHUB_TOKEN: ${{ inputs.github-token }}

      - name: Creates a Release with a changelog from a Milestone
        uses: rosestack/milestone-release-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          milestone-title: ${{ env.RELEASE_VERSION }}
          milestone-next: ${{ env.NEXT_BRANCH }}
