# https://www.lorenzobettini.it/2020/01/publishing-a-maven-site-to-github-pages

name: Maven Site and Publish

on:
  workflow_call:
    inputs:
      java:
        default: '8'
        required: false
        type: string

      java-dist:
        default: 'zulu'
        required: false
        type: string

env:
  MAVEN_ARGS: -B -U -ntp

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java ${{ inputs.Java }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.Java-dist }}
          java-version: ${{ inputs.Java }}
          cache: maven
          server-id: github
          server-username: ${{ secrets.GITHUB_ACTOR }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Maven Site
        run: |
          mvn package site:site site:stage scm-publish:publish-scm
