# https://github.com/s4u/.github/blob/master/.github/workflows/maven-build.yml

name: Maven Deploy

on:
  workflow_call:
    inputs:
      java-default:
        default: '8'
        required: false
        type: string

      java-dist-default:
        default: 'zulu'
        required: false
        type: string

    secrets:
      OSSRH_USERNAME:
        required: true

      OSSRH_PASSWORD:
        required: true

      GPG_SECRET_KEY:
        required: true

      GPG_PASSPHRASE:
        required: true

  workflow_dispatch:
    inputs:
      java-default:
        description: Java version to use
        default: '8'
        required: false
        type: string

      java-dist-default:
        description: Java distribution to use
        default: 'zulu'
        required: false
        type: string

env:
  MAVEN_ARGS: -B -U -ntp

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Java ${{ inputs.java-default }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-default }}
          distribution: ${{ inputs.java-dist-default }}
          cache: maven
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }} # macOS: gpg --armor --export-secret-key

      - run: mvn -DskipTests -Prelease deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
