# https://github.com/kanezi/boot-render-deploy/blob/master/.github/workflows/docker-publish.yml

name: Maven Docker

on:
  workflow_call:
    inputs:
      java-default:
        default: '8'
        required: false
        type: string

      java-dist-default:
        default: 'zulu'
        required: false
        type: string

  workflow_dispatch:
    inputs:
      java-default:
        description: Java version to use
        default: '8'
        required: false
        type: string

      java-dist-default:
        description: Java distribution to use
        default: 'zulu'
        required: false
        type: string
env:
  MAVEN_ARGS: -B -U -ntp
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    uses: ./.github/workflows/maven-build.yml
    secrets: inherit
    with:
      java-default: ${{ inputs.java-default }}
      java-dist-default: ${{ inputs.java-dist-default }}

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "TAG=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\/v//')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Publish Docker Image
        run: |
          mvn spring-boot:build-image -DskipTests
          docker tag ${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}:$TAG
          echo "Pushing the image ${{ env.IMAGE_NAME }} to Docker Hub..."
          docker push --all-tags ${{ env.IMAGE_NAME }}