name: Maven Build and Docker

on:
  workflow_call:
    inputs:
      java-default:
        default: '8'
        required: false
        type: string

      java-dist-default:
        default: 'zulu'
        required: false
        type: string

env:
  MAVEN_ARGS: -B -U -ntp

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "TAG=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\///')" >> $GITHUB_ENV
          echo "REPO_NAME=$(echo ${{ github.repository }} | awk -F '/' '{print $2}')" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_NAME=${{ github.DOCKER_USERNAME }}/${REPO_NAME}" >> $GITHUB_ENV  

      - name: Setup Java ${{ matrix.Java }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.java-dist }}
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Build with Maven
        run: mvn verify

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Publish Docker Image
        run: |
          mvn spring-boot:build-image -DskipTests
          docker tag $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME:$TAG
          echo "Pushing the image $DOCKER_IMAGE_NAME to Docker Hub..."
          docker push --all-tags $DOCKER_IMAGE_NAME