# https://github.com/s4u/.github/blob/master/.github/workflows/maven-build.yml

name: Maven All

on:
  workflow_call:
    inputs:
      os:
        default: '["windows-latest", "ubuntu-latest", "macOs-latest"]'
        required: false
        type: string

      java-matrix:
        default: '["8", "11", "17", "21", "24"]'
        required: false
        type: string

      java-dist-matrix:
        default: '["zulu"]'
        required: false
        type: string

      java-default:
        default: '8'
        required: false
        type: string

      java-dist-default:
        default: 'zulu'
        required: false
        type: string

      sonar-host:
        default: 'https://sonarcloud.io/'
        required: false
        type: string

      sonar-organization:
        default: 'rosestack'
        required: false
        type: string

  workflow_dispatch:
    inputs:
      os:
        description: OS
        default: '["windows-latest", "ubuntu-latest", "macOs-latest"]'
        required: false
        type: string

      java-matrix:
        description: Java Version
        default: '["8", "11", "17", "21", "24"]'
        required: false
        type: string

      java-dist-matrix:
        description: Java Distribution
        default: '["zulu"]'
        required: false
        type: string

      java-default:
        description: Java Default Version
        default: '8'
        required: false
        type: string

      java-dist-default:
        description: Java Default Distribution
        default: 'zulu'
        required: false

      sonar-host:
        description: Sonar Host
        default: 'https://sonarcloud.io/'
        required: false
        type: string

      sonar-organization:
        description: Sonar Organization
        default: 'rosestack'
        required: false
        type: string

jobs:
  build:
    uses: ./.github/workflows/maven-build.yml
    secrets: inherit
    with:
      os: ${{ inputs.os }}
      java-matrix: ${{ inputs.java-matrix }}
      java-dist-matrix: ${{ inputs.java-dist-matrix }}
      sonar-host: ${{ inputs.sonar-host }}
      sonar-organization: ${{ inputs.sonar-organization }}

  deploy:
    uses: ./.github/workflows/maven-deploy.yml
    secrets: inherit
    with:
      java-default: ${{ inputs.java-default }}
      java-dist-default: ${{ inputs.java-dist-default }}

  site:
    uses: ./.github/workflows/maven-site.yml
    secrets: inherit
    with:
      java-default: ${{ inputs.java-default }}
      java-dist-default: ${{ inputs.java-dist-default }}