name: Maven Prepare Release

## Step:
## 1. Create release branch in local
## 2. mvn release:prepare release:clean
## 3. Delete release branch
## 4. push tag -> trigger release workflow

on:
  workflow_call:
    inputs:
      release-version:
        description: "Release version"
        required: true
        type: string
        default: "0.0.1"
      next-version:
        description: "Next version"
        required: true
        type: string
        default: "0.0.2-SNAPSHOT"


  workflow_dispatch:
    inputs:
      release-version:
        description: "Release version"
        required: true
        type: string
        default: "0.0.1"
      next-version:
        description: "Next version"
        required: true
        type: string
        default: "0.0.2-SNAPSHOT"

env:
  MAVEN_ARGS: -B -U -ntp

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "RELEASE_VERSION=${DISPATCH_RELEASE_VERSION}" >> $GITHUB_ENV
          echo "NEXT_VERSION=${DISPATCH_NEXT_VERSION}" >> $GITHUB_ENV
        env:
          DISPATCH_RELEASE_VERSION: ${{ inputs.release-version }}
          DISPATCH_NEXT_VERSION: ${{ inputs.next-version }}

      - name: Validate version
        if: contains(env.RELEASE_VERSION, 'SNAPSHOT')
        run: |
          echo '::error::Cannot release a SNAPSHOT version.'
          exit 1

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Get version
        run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "VERSION=$VERSION"
          if [[ $VERSION != *-SNAPSHOT ]]; then
            echo "::error::You don't have a SNAPSHOT project in the projects list."
            exit 1
          fi

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Build Prepare Release with Maven
        timeout-minutes: 120
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo $BRANCH

          git checkout -b "release-$RELEASE_VERSION"

          mvn release:prepare -DinteractiveMode=false -DreleaseVersion=$RELEASE_VERSION -DdevelopmentVersion=$NEXT_VERSION
          mvn release:clean

          git push origin "release-$RELEASE_VERSION"

          git checkout $BRANCH

          git branch -D "release-$RELEASE_VERSION"

          git push --tags

      - name: Creates a Release with a changelog from a Milestone
        uses: rosestack/milestone-release-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          milestone-title: ${{ env.RELEASE_VERSION }}
          milestone-next: ${{ env.NEXT_BRANCH }}
