name: Maven Release by File

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]
    paths:
      - '.github/project.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: rosestack/maven-release-by-file-action@v1