name: Maven Release by File

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]
    paths:
      - '.github/project.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: rosestack/maven-release-by-file-action@v1
        with:
          gpg-secret-key: ${{secrets.GPG_SECRET_KEY}}
          signing-passphrase: ${{secrets.SIGNING_PASSPHRASE}}
          ossrh-username: ${{secrets.OSSRH_USERNAME}}
          ossrh-password: ${{secrets.OSSRH_PASSWORD}}
          github-token: ${{secrets.GITHUB_TOKEN}}
