name: Publish Site with Maven

on:
  workflow_call:
    inputs:
      multi_modules:
        description: "Multi modules ?"
        required: false
        type: boolean
        default: false

env:
  MAVEN_ARGS: -B -U -ntp

jobs:
  site:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "MULTI_MODULES=${DISPATCH_MULTI_MODULES}" >> $GITHUB_ENV
        env:
          DISPATCH_MULTI_MODULES: ${{ inputs.multi_modules }}

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Maven Site
        run: |
          if [ "$MULTI_MODULES" == true ]; then
            mvn install site:site site:stage scm-publish:publish-scm -Dscmpublish.serverId=github
          else
            mvn install site:site scm-publish:publish-scm -Dscmpublish.serverId=github
          fi
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}