name: Publish Site with Maven

on:
  workflow_call:
    inputs:
      multi-modules:
        description: "Multi modules ?"
        required: false
        type: boolean
        default: false

env:
  MAVEN_ARGS: -B -U -ntp

jobs:
  site:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '8' ]

    steps:
      - name: Set Environment Variables
        run: |
          echo "MULTI_MODULES=${{github.event.inputs.multi-modules}}" >> $GITHUB_ENV

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.Java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Maven Site
        run: |
          if [ "$MULTI_MODULES" = true ]; then
            mvn install site:site site:stage
          else
            mvn install site:site
          fi
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/staging/
          commit_message: 'Deploy to pages'
