name: Publish Site with Maven

on:
  workflow_call:

env:
  MAVEN_ARGS: -B -ntp

jobs:
  site:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '8' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create gh-pages
        run: |
          git pull
          git branch -d gh-pages
          git branch gh-pages
          git branch
          git push origin gh-pages

      - name: Java ${{ matrix.Java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Config git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Publish site to github pages
        run: |
          mvn --update-snapshots clean site scm-publish:publish-scm -Dscmpublish.serverId=github
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}